export const getLink = (fileName: string): string => {
  const path: string = filePathMap[fileName];
  return path ? path : '';
};

const filePathMap: Record<string, string> = {
  "КА-1 Общий вид.fxml": "/sverdlovsk/novosverdlovskaya/ka-1_obshchiy_vid",
  "КА-1 Барабан.fxml": "/sverdlovsk/novosverdlovskaya/ka-1_baraban",
  "КА-1 Газ.fxml": "/sverdlovsk/novosverdlovskaya/ka-1_gaz",
  "КА-1 Газовоздушный тракт.fxml": "/sverdlovsk/novosverdlovskaya/ka-1_gazovozdushnyy_trakt",
  "КА-1 Защиты 1.fxml": "/sverdlovsk/novosverdlovskaya/ka-1_zashchity_1",
  "КА-1 Защиты 2.fxml": "/sverdlovsk/novosverdlovskaya/ka-1_zashchity_2",
  "КА-1 Защиты 3.fxml": "/sverdlovsk/novosverdlovskaya/ka-1_zashchity_3",
  "КА-1 Сигнализации.fxml": "/sverdlovsk/novosverdlovskaya/ka-1_signalizacii",
  "КА-1 Термоконтроль.fxml": "/sverdlovsk/novosverdlovskaya/ka-1_termokontrol",
  "КА-1 Управление газовыми блоками.fxml": "/sverdlovsk/novosverdlovskaya/ka-1_upravlenie_gazovymi_blokami",
  "КА-1 Пароводяной тракт.fxml": "/sverdlovsk/novosverdlovskaya/ka-1_parovodyanoy_trakt",
  "КА-1 Сигналы КА.fxml": "/sverdlovsk/novosverdlovskaya/ka-1_signaly_ka",

  "КА-2 Общий вид.fxml": "/sverdlovsk/novosverdlovskaya/ka-2_obshchiy_vid",
  "КА-2 Барабан.fxml": "/sverdlovsk/novosverdlovskaya/ka-2_baraban",
  "КА-2 Газ.fxml": "/sverdlovsk/novosverdlovskaya/ka-2_gaz",
  "КА-2 Газовоздушный тракт.fxml": "/sverdlovsk/novosverdlovskaya/ka-2_gazovozdushnyy_trakt",
  "КА-2 Защиты.fxml": "/sverdlovsk/novosverdlovskaya/ka-2_zashchity",
  "КА-2 Термоконтроль.fxml": "/sverdlovsk/novosverdlovskaya/ka-2_termokontrol",
  "КА-2 Пароводяной тракт.fxml": "/sverdlovsk/novosverdlovskaya/ka-2_parovodyanoy_trakt",
  "КА-2 Сигналы КА.fxml": "/sverdlovsk/novosverdlovskaya/ka-2_signaly_ka",



  "КА-3 Общий вид.fxml": "/sverdlovsk/novosverdlovskaya/ka-3_obshchiy_vid",
  "КА-3 Барабан.fxml": "/sverdlovsk/novosverdlovskaya/ka-3_baraban",
  "КА-3 Газ.fxml": "/sverdlovsk/novosverdlovskaya/ka-3_gaz",
  "КА-3 Газовоздушный тракт.fxml": "/sverdlovsk/novosverdlovskaya/ka-3_gazovozdushnyy_trakt",
  "КА-3 Защиты.fxml": "/sverdlovsk/novosverdlovskaya/ka-3_zashchity",
  "КА-3 Термоконтроль.fxml": "/sverdlovsk/novosverdlovskaya/ka-3_termokontrol",
  "КА-3 Пароводяной тракт.fxml": "/sverdlovsk/novosverdlovskaya/ka-3_parovodyanoy_trakt",
  "КА-3 Сигналы КА.fxml": "/sverdlovsk/novosverdlovskaya/ka-4_signaly_ka",

  "КА-4 Общий вид.fxml": "/sverdlovsk/novosverdlovskaya/ka-4_obshchiy_vid",
  "КА-4 Барабан.fxml": "/sverdlovsk/novosverdlovskaya/ka-4_baraban",
  "КА-4 Газ.fxml": "/sverdlovsk/novosverdlovskaya/ka-4_gaz",
  "КА-4 Газовоздушный тракт.fxml": "/sverdlovsk/novosverdlovskaya/ka-4_gazovozdushnyy_trakt",
  "КА-4 Защиты.fxml": "/sverdlovsk/novosverdlovskaya/ka-4_zashchity",
  "КА-4 Термоконтроль.fxml": "/sverdlovsk/novosverdlovskaya/ka-4_termokontrol",
  "КА-4 Пароводяной тракт.fxml": "/sverdlovsk/novosverdlovskaya/ka-4_parovodyanoy_trakt",
  "КА-4 Сигналы КА.fxml": "/sverdlovsk/novosverdlovskaya/ka-4_signaly_ka",

  "КА-5 Общий вид.fxml": "/sverdlovsk/novosverdlovskaya/ka-5_obshchiy_vid",
  "КА-5 Барабан.fxml": "/sverdlovsk/novosverdlovskaya/ka-5_baraban",
  "КА-5 Газ.fxml": "/sverdlovsk/novosverdlovskaya/ka-5_gaz",
  "КА-5 Газовоздушный тракт.fxml": "/sverdlovsk/novosverdlovskaya/ka-5_gazovozdushnyy_trakt",
  "КА-5 Защиты 1.fxml": "/sverdlovsk/novosverdlovskaya/ka-5_zashchity_1",
  "КА-5 Защиты 2.fxml": "/sverdlovsk/novosverdlovskaya/ka-5_zashchity_2",
  "КА-5 Защиты 3.fxml": "/sverdlovsk/novosverdlovskaya/ka-5_zashchity_3",
  "КА-5 Сигнализации.fxml": "/sverdlovsk/novosverdlovskaya/ka-5_signalizacii",
  "КА-5 Термоконтроль.fxml": "/sverdlovsk/novosverdlovskaya/ka-5_termokontrol",
  "КА-5 Управление газовыми блоками.fxml": "/sverdlovsk/novosverdlovskaya/ka-5_upravlenie_gazovymi_blokami",
  "КА-5 Пароводяной тракт.fxml": "/sverdlovsk/novosverdlovskaya/ka-5_parovodyanoy_trakt",
  "КА-5 Сигналы КА.fxml": "/sverdlovsk/novosverdlovskaya/ka-5_signaly_ka",

  "КА-6 Общий вид.fxml": "/sverdlovsk/novosverdlovskaya/ka-6_obshchiy_vid",
  "КА-6 Барабан.fxml": "/sverdlovsk/novosverdlovskaya/ka-6_baraban",
  "КА-6 Газ.fxml": "/sverdlovsk/novosverdlovskaya/ka-6_gaz",
  "КА-6 Газовоздушный тракт.fxml": "/sverdlovsk/novosverdlovskaya/ka-6_gazovozdushnyy_trakt",
  "КА-6 Защиты.fxml": "/sverdlovsk/novosverdlovskaya/ka-6_zashchity",
  "КА-6 Термоконтроль.fxml": "/sverdlovsk/novosverdlovskaya/ka-6_termokontrol",
  "КА-6 Пароводяной тракт.fxml": "/sverdlovsk/novosverdlovskaya/ka-6_parovodyanoy_trakt",
  "КА-6 Сигналы КА.fxml": "/sverdlovsk/novosverdlovskaya/ka-6_signaly_ka",

  "КА-7 Общий вид.fxml": "/sverdlovsk/novosverdlovskaya/ka-7_obshchiy_vid",
  "КА-7 Барабан.fxml": "/sverdlovsk/novosverdlovskaya/ka-7_baraban",
  "КА-7 Газ.fxml": "/sverdlovsk/novosverdlovskaya/ka-7_gaz",
  "КА-7 Газовоздушный тракт.fxml": "/sverdlovsk/novosverdlovskaya/ka-7_gazovozdushnyy_trakt",
  "КА-7 Защиты.fxml": "/sverdlovsk/novosverdlovskaya/ka-7_zashchity",
  "КА-7 Термоконтроль.fxml": "/sverdlovsk/novosverdlovskaya/ka-7_termokontrol",
  "КА-7 Пароводяной тракт.fxml": "/sverdlovsk/novosverdlovskaya/ka-7_parovodyanoy_trakt",
  "КА-7 Сигналы КА.fxml": "/sverdlovsk/novosverdlovskaya/ka-7_signaly_ka",

  "КА-8 Общий вид.fxml": "/sverdlovsk/novosverdlovskaya/ka-8_obshchiy_vid",
  "КА-8 Барабан.fxml": "/sverdlovsk/novosverdlovskaya/ka-8_baraban",
  "КА-8 Газ.fxml": "/sverdlovsk/novosverdlovskaya/ka-8_gaz",
  "КА-8 Газовоздушный тракт.fxml": "/sverdlovsk/novosverdlovskaya/ka-8_gazovozdushnyy_trakt",
  "КА-8 Защиты 1.fxml": "/sverdlovsk/novosverdlovskaya/ka-8_zashchity_1",
  "КА-8 Защиты 2.fxml": "/sverdlovsk/novosverdlovskaya/ka-8_zashchity_2",
  "КА-8 Защиты 3.fxml": "/sverdlovsk/novosverdlovskaya/ka-8_zashchity_3",

  "КА-8 Сигнализации.fxml": "/sverdlovsk/novosverdlovskaya/ka-8_signalizacii",
  "КА-8 Термоконтроль.fxml": "/sverdlovsk/novosverdlovskaya/ka-8_termokontrol",
  "КА-8 Управление газовыми блоками.fxml": "/sverdlovsk/novosverdlovskaya/ka-8_upravlenie_gazovymi_blokami",
  "КА-8 Пароводяной тракт.fxml": "/sverdlovsk/novosverdlovskaya/ka-8_parovodyanoy_trakt",
  "КА-8 Сигналы КА.fxml": "/sverdlovsk/novosverdlovskaya/ka-8_signaly_ka",


  "ТА-1 Генератор (охлаждение).fxml": "/sverdlovsk/novosverdlovskaya/ta-1_generator_ohlazhdenie",
  "ТА-1 Генератор (УВГ).fxml": "/sverdlovsk/novosverdlovskaya/ta-1_generator_(uvg)",
  "ТА-1 Грязное масло ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-1_gryaznoe_maslo_ta",
  "ТА-1 Защиты ТА(ПВД, ПСГ).fxml": "/sverdlovsk/novosverdlovskaya/ta-1_zashchity_ta(pvd,_psg)",
  "ТА-1 Защиты ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-1_zashchity_ta",
  "ТА-1 Конденсатор.fxml": "/sverdlovsk/novosverdlovskaya/ta-1_kondensator",
  "ТА-1 Маслоснабжение.fxml": "/sverdlovsk/novosverdlovskaya/ta-1_maslosnabzhenie",
  "ТА-1 Мех. величины.fxml": "/sverdlovsk/novosverdlovskaya/ta-1_meh_velichiny",
  "ТА-1 Общий.fxml": "/sverdlovsk/novosverdlovskaya/ta-1_obshchiy",
  "ТА-1 ОК.fxml": "/sverdlovsk/novosverdlovskaya/ta-1_ok",
  "ТА-1 ПСГ.fxml": "/sverdlovsk/novosverdlovskaya/ta-1_psg",
  "ТА-1 Пульт управления.fxml": "/sverdlovsk/novosverdlovskaya/ta-1_pult_upravleniya",
  "ТА-1 Рабочее масло.fxml": "/sverdlovsk/novosverdlovskaya/ta-1_rabochee_maslo",
  "ТА-1 Сигнализации ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-1_signalizacii_ta",
  "ТА-1 Система регенерации ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-1_sistema_regeneracii_ta",
  "ТА-1 Техническая вода.fxml": "/sverdlovsk/novosverdlovskaya/ta-1_tehnicheskaya_voda",
  "ТА-1 Уплотнения ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-1_uplotneniya_ta",

  "ТА-2 Генератор (охлаждение).fxml": "/sverdlovsk/novosverdlovskaya/ta-2_generator_ohlazhdenie",
  "ТА-2 Генератор (УВГ).fxml": "/sverdlovsk/novosverdlovskaya/ta-2_generator_(uvg)",
  "ТА-2 Грязное масло ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-2_gryaznoe_maslo_ta",
  "ТА-2 Защиты ТА(ПВД, ПСГ).fxml": "/sverdlovsk/novosverdlovskaya/ta-2_zashchity_ta(pvd,_psg)",
  "ТА-2 Защиты ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-2_zashchity_ta",
  "ТА-2 Конденсатор.fxml": "/sverdlovsk/novosverdlovskaya/ta-2_kondensator",
  "ТА-2 Маслоснабжение.fxml": "/sverdlovsk/novosverdlovskaya/ta-2_maslosnabzhenie",
  "ТА-2 Мех. величины.fxml": "/sverdlovsk/novosverdlovskaya/ta-2_meh_velichiny",
  "ТА-2 Общий.fxml": "/sverdlovsk/novosverdlovskaya/ta-2_obshchiy",
  "ТА-2 ОК.fxml": "/sverdlovsk/novosverdlovskaya/ta-2_ok",
  "ТА-2 ПСГ.fxml": "/sverdlovsk/novosverdlovskaya/ta-2_psg",
  "ТА-2 Пульт управления.fxml": "/sverdlovsk/novosverdlovskaya/ta-2_pult_upravleniya",
  "ТА-2 Рабочее масло.fxml": "/sverdlovsk/novosverdlovskaya/ta-2_rabochee_maslo",
  "ТА-2 Сигнализации ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-2_signalizacii_ta",
  "ТА-2 Система регенерации ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-2_sistema_regeneracii_ta",
  "ТА-2 Техническая вода.fxml": "/sverdlovsk/novosverdlovskaya/ta-2_tehnicheskaya_voda",
  "ТА-2 Уплотнения ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-2_uplotneniya_ta",

  "ТА-3 Генератор (охлаждение).fxml": "/sverdlovsk/novosverdlovskaya/ta-3_generator_ohlazhdenie",
  "ТА-3 Генератор (УВГ).fxml": "/sverdlovsk/novosverdlovskaya/ta-3_generator_(uvg)",
  "ТА-3 Грязное масло ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-3_gryaznoe_maslo_ta",
  "ТА-3 Защиты ТА(ПВД, ПСГ).fxml": "/sverdlovsk/novosverdlovskaya/ta-3_zashchity_ta(pvd,_psg)",
  "ТА-3 Защиты ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-3_zashchity_ta",
  "ТА-3 Конденсатор.fxml": "/sverdlovsk/novosverdlovskaya/ta-3_kondensator",
  "ТА-3 Маслоснабжение.fxml": "/sverdlovsk/novosverdlovskaya/ta-3_maslosnabzhenie",
  "ТА-3 Мех. величины.fxml": "/sverdlovsk/novosverdlovskaya/ta-3_meh_velichiny",
  "ТА-3 Общий.fxml": "/sverdlovsk/novosverdlovskaya/ta-3_obshchiy",
  "ТА-3 ОК.fxml": "/sverdlovsk/novosverdlovskaya/ta-3_ok",
  "ТА-3 ПСГ.fxml": "/sverdlovsk/novosverdlovskaya/ta-3_psg",
  "ТА-3 Пульт управления.fxml": "/sverdlovsk/novosverdlovskaya/ta-3_pult_upravleniya",
  "ТА-3 Рабочее масло.fxml": "/sverdlovsk/novosverdlovskaya/ta-3_rabochee_maslo",
  "ТА-3 Сигнализации ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-3_signalizacii_ta",
  "ТА-3 Система регенерации ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-3_sistema_regeneracii_ta",
  "ТА-3 Техническая вода.fxml": "/sverdlovsk/novosverdlovskaya/ta-3_tehnicheskaya_voda",
  "ТА-3 Уплотнения ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-3_uplotneniya_ta",

  "ТА-4 Генератор (охлаждение).fxml": "/sverdlovsk/novosverdlovskaya/ta-4_generator_ohlazhdenie",
  "ТА-4 Генератор (УВГ).fxml": "/sverdlovsk/novosverdlovskaya/ta-4_generator_(uvg)",
  "ТА-4 Грязное масло ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-4_gryaznoe_maslo_ta",
  "ТА-4 Защиты ТА(ПВД, ПСГ).fxml": "/sverdlovsk/novosverdlovskaya/ta-4_zashchity_ta(pvd,_psg)",
  "ТА-4 Защиты ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-4_zashchity_ta",
  "ТА-4 Конденсатор.fxml": "/sverdlovsk/novosverdlovskaya/ta-4_kondensator",
  "ТА-4 Маслоснабжение.fxml": "/sverdlovsk/novosverdlovskaya/ta-4_maslosnabzhenie",
  "ТА-4 Мех. величины.fxml": "/sverdlovsk/novosverdlovskaya/ta-4_meh_velichiny",
  "ТА-4 Общий.fxml": "/sverdlovsk/novosverdlovskaya/ta-4_obshchiy",
  "ТА-4 ОК.fxml": "/sverdlovsk/novosverdlovskaya/ta-4_ok",
  "ТА-4 ПСГ.fxml": "/sverdlovsk/novosverdlovskaya/ta-4_psg",
  "ТА-4 Пульт управления.fxml": "/sverdlovsk/novosverdlovskaya/ta-4_pult_upravleniya",
  "ТА-4 Рабочее масло.fxml": "/sverdlovsk/novosverdlovskaya/ta-4_rabochee_maslo",
  "ТА-4 Сигнализации ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-4_signalizacii_ta",
  "ТА-4 Система регенерации ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-4_sistema_regeneracii_ta",
  "ТА-4 Техническая вода.fxml": "/sverdlovsk/novosverdlovskaya/ta-4_tehnicheskaya_voda",
  "ТА-4 Уплотнения ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-4_uplotneniya_ta",

  "ТА-5 Генератор (охлаждение).fxml": "/sverdlovsk/novosverdlovskaya/ta-5_generator_ohlazhdenie",
  "ТА-5 Генератор (УВГ).fxml": "/sverdlovsk/novosverdlovskaya/ta-5_generator_(uvg)",
  "ТА-5 Грязное масло ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-5_gryaznoe_maslo_ta",
  "ТА-5 Защиты ТА(ПВД, ПСГ).fxml": "/sverdlovsk/novosverdlovskaya/ta-5_zashchity_ta(pvd,_psg)",
  "ТА-5 Защиты ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-5_zashchity_ta",
  "ТА-5 Конденсатор.fxml": "/sverdlovsk/novosverdlovskaya/ta-5_kondensator",
  "ТА-5 Маслоснабжение.fxml": "/sverdlovsk/novosverdlovskaya/ta-5_maslosnabzhenie",
  "ТА-5 Мех. величины.fxml": "/sverdlovsk/novosverdlovskaya/ta-5_meh_velichiny",
  "ТА-5 Общий.fxml": "/sverdlovsk/novosverdlovskaya/ta-5_obshchiy",
  "ТА-5 ОК.fxml": "/sverdlovsk/novosverdlovskaya/ta-5_ok",
  "ТА-5 ПСГ.fxml": "/sverdlovsk/novosverdlovskaya/ta-5_psg",
  "ТА-5 Пульт управления.fxml": "/sverdlovsk/novosverdlovskaya/ta-5_pult_upravleniya",
  "ТА-5 Рабочее масло.fxml": "/sverdlovsk/novosverdlovskaya/ta-5_rabochee_maslo",
  "ТА-5 Сигнализации ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-5_signalizacii_ta",
  "ТА-5 Система регенерации ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-5_sistema_regeneracii_ta",
  "ТА-5 Техническая вода.fxml": "/sverdlovsk/novosverdlovskaya/ta-5_tehnicheskaya_voda",
  "ТА-5 Уплотнения ТА.fxml": "/sverdlovsk/novosverdlovskaya/ta-5_uplotneniya_ta",
 
  
  "ОСО Общая схема.fxml": "/sverdlovsk/novosverdlovskaya/oso_obshchaya_shema",
  "ОСО Сетевая вода.fxml": "/sverdlovsk/novosverdlovskaya/oso_setevaya_voda",
  "ОСО Подпитка С.В..fxml": "/sverdlovsk/novosverdlovskaya/oso_podpitka_s_v",
  "ОСО РРОУ, ОРОУ.fxml": "/sverdlovsk/novosverdlovskaya/oso_rrou_orou",
  "ОСО Пар КСН.fxml": "/sverdlovsk/novosverdlovskaya/oso_par_ksn",
  "ОСО Вак. деаэраторы.fxml": "/sverdlovsk/novosverdlovskaya/oso_vak_deaeratory",
  "ОСО Пар ПВК.fxml": "/sverdlovsk/novosverdlovskaya/oso_par_pvk",
  "ОСО СВСНЦ.fxml": "/sverdlovsk/novosverdlovskaya/oso_svsnc",
  "ОСО НВВ.fxml": "/sverdlovsk/novosverdlovskaya/oso_nvv",
  "ОСО Коллектор ОК ГК.fxml": "/sverdlovsk/novosverdlovskaya/oso_kollektor_ok_gk",
  "ОСО Тех. вода ГК - 1.fxml": "/sverdlovsk/novosverdlovskaya/oso_teh_voda_gk_-_1",
  "ОСО Тех. вода ГК - 2.fxml": "/sverdlovsk/novosverdlovskaya/oso_teh_voda_gk_-_2",
  "ОСО Тех. вода ГК - 3.fxml": "/sverdlovsk/novosverdlovskaya/oso_teh_voda_gk_-_3",
  "ОСО Цирк. Вода.fxml": "/sverdlovsk/novosverdlovskaya/oso_cirk_voda",
  "ОСО ОВ генераторов с НГО.fxml": "/sverdlovsk/novosverdlovskaya/oso_ov_generatorov_s_ngo",
  "ОСО Аккумуляторный бак.fxml": "/sverdlovsk/novosverdlovskaya/oso_akkumulyatornyy_bak",
  "ОСО Водопроводная вода.fxml": "/sverdlovsk/novosverdlovskaya/oso_vodoprovodnaya_voda",
  "ОСО Защиты ПБ.fxml": "/sverdlovsk/novosverdlovskaya/oso_zashchity_pb",
  "ОСО ГРП.fxml": "/sverdlovsk/novosverdlovskaya/oso_grp",
  "ОСО НВР.fxml": "/sverdlovsk/novosverdlovskaya/oso_nvr",
  "ОСО НГС.fxml": "/sverdlovsk/novosverdlovskaya/oso_ngs",


  "СН-I Общий кадр.fxml": "/sverdlovsk/novosverdlovskaya/sn-1_obshchiy_kadr",

  "СН II Защиты.fxml": "/sverdlovsk/novosverdlovskaya/oso_ngs",
  "СН II Маслостанция и охл.вода СН 21.fxml": "/sverdlovsk/novosverdlovskaya/sn_2_maslostanciya_i_ohl_voda_sn_21",
  "СН II Маслостанция и охл.вода СН 22.fxml": "/sverdlovsk/novosverdlovskaya/sn_2_maslostanciya_i_ohl_Voda_sn_22",
  "СН II Маслостанция и охл.вода СН 23.fxml": "/sverdlovsk/novosverdlovskaya/sn_2_maslostanciya_i_ohl_Voda_sn_23",
  "СН II Маслостанция и охл.вода СН 24.fxml": "/sverdlovsk/novosverdlovskaya/sn_2_maslostanciya_i_ohl_Voda_sn_24",
  "СН II Маслостанция и охл.вода СН 25.fxml": "/sverdlovsk/novosverdlovskaya/sn_2_maslostanciya_i_ohl_Voda_sn_25",
  "СН II Маслостанция и охл.вода СН 26.fxml": "/sverdlovsk/novosverdlovskaya/sn_2_maslostanciya_i_ohl_Voda_sn_26",
  "СН II Маслостанция и охл.вода СН 27.fxml": "/sverdlovsk/novosverdlovskaya/sn_2_maslostanciya_i_ohl_Voda_sn_27",
  "СН II Маслостанция и охл.вода СН 28.fxml": "/sverdlovsk/novosverdlovskaya/sn_2_maslostanciya_i_ohl_Voda_sn_28",
  "СН II Общий кадр.fxml": "/sverdlovsk/novosverdlovskaya/sn-2_obshchiy_kadr",
  
  "ПВ ГК Масло и водоснабжение ПЭН-1.fxml": "/sverdlovsk/novosverdlovskaya/pv_gk_maslo_i_vodosnabzhenie_pen-1",
  "ПВ ГК Масло и водоснабжение ПЭН-2.fxml": "/sverdlovsk/novosverdlovskaya/pv_gk_maslo_i_vodosnabzhenie_pen-2",
  "ПВ ГК Масло и водоснабжение ПЭН-3.fxml": "/sverdlovsk/novosverdlovskaya/pv_gk_maslo_i_vodosnabzhenie_pen-3",
  "ПВ ГК Масло и водоснабжение ПЭН-4.fxml": "/sverdlovsk/novosverdlovskaya/pv_gk_maslo_i_vodosnabzhenie_pen-4",
  "ПВ ГК Масло и водоснабжение ПЭН-5.fxml": "/sverdlovsk/novosverdlovskaya/pv_gk_maslo_i_vodosnabzhenie_pen-5",
  "ПВ ГК Масло и водоснабжение ПЭН-6.fxml": "/sverdlovsk/novosverdlovskaya/pv_gk_maslo_i_vodosnabzhenie_pen-6",
  "ПВ ГК Общая.fxml": "/sverdlovsk/novosverdlovskaya/pv_gk_obshchaya",
  "ПЭН №1.2 защиты,сигнал, АВР.fxml": "/sverdlovsk/novosverdlovskaya/pen_no1_2_zashchity,signal,_avr",
  "ПЭН №3.4 защиты,сигнал, АВР.fxml": "/sverdlovsk/novosverdlovskaya/pen_no3_4_zashchity,signal,_avr",
  "ПЭН №5.6 защиты,сигнал, АВР.fxml": "/sverdlovsk/novosverdlovskaya/pen_no5_6_zashchity,signal,_avr",

// ЭСО
  "ЭСО КРУ 11РА 11РБ.fxml": "/sverdlovsk/novosverdlovskaya/eso_kru_11ra_11rb",
  "ЭСО КРУ 21РБ 21РА 31РА.fxml": "/sverdlovsk/novosverdlovskaya/eso_kru_21rb_21ra_31ra",
  "ЭСО КРУ 41РА-1 41РА-2 51РА.fxml": "/sverdlovsk/novosverdlovskaya/eso_kru_41ra-1_41ra-2_51ra",
  "ЭСО Генераторы.fxml": "/sverdlovsk/novosverdlovskaya/eso_generatory",
  "ЭСО КРУ-6 кВ (1).fxml": "/sverdlovsk/novosverdlovskaya/eso_kru-6_kv_1",
  "ЭСО КРУ-6 кВ (2).fxml": "/sverdlovsk/novosverdlovskaya/eso_kru-6_kv_2",
  "ЭСО Общая схема 1.fxml": "/sverdlovsk/novosverdlovskaya/eso_obshchaya_shema_1",
  "ЭСО Общая схема 2.fxml": "/sverdlovsk/novosverdlovskaya/eso_obshchaya_shema_2",
  "ЭСО ОРУ 110 кВ 1.fxml": "/sverdlovsk/novosverdlovskaya/eso_oru_110_kv_1",
  "ЭСО ОРУ 110 кВ 2.fxml": "/sverdlovsk/novosverdlovskaya/eso_oru_110_kv_2",
  "ЭСО ОРУ 220 кВ.fxml": "/sverdlovsk/novosverdlovskaya/eso_oru_220_kv",
  "ЭСО Электросеть.fxml": "/sverdlovsk/novosverdlovskaya/eso_elektroset",



  // academic

  //ДКС
  "Compressor Overview (Общая ДК1).fxml": "/sverdlovsk/academic/compressor_overview_dk1",
  "Controls (Регуляторы ДК1).fxml": "/sverdlovsk/academic/controls_dk1",
  "Machine ( Оборудование ДК1).fxml": "/sverdlovsk/academic/machine_dk1",
  "Oil system (Масляная система ДК1).fxml": "/sverdlovsk/academic/oil_system_dk1",
  "Seal gas - st.1 (Упл. Газ ст.1 ДК1).fxml": "/sverdlovsk/academic/seal_gas_st1_dk1",
  "Seal gas - st.2,3 (Упл. Газ ст.2,3 ДК1).fxml": "/sverdlovsk/academic/seal_gas_st2-3_dk1",
  "Gas system (Газовая система ДК1).fxml": "/sverdlovsk/academic/gas_system_dk1",
  "Sensors (Датчики ДК1).fxml": "/sverdlovsk/academic/sensors_dk1",
  "Sensors MMS (Датчики MMS ДК1).fxml": "/sverdlovsk/academic/sensors_mms_dk1",
  "Compressor Overview (Общая ДК2).fxml": "/sverdlovsk/academic/compressor_overview_dk2",
  "Controls (Регуляторы ДК2).fxml": "/sverdlovsk/academic/controls_dk2",
  "Machine ( Оборудование ДК2).fxml": "/sverdlovsk/academic/machine_dk2",
  "Oil system (Масляная система ДК2).fxml": "/sverdlovsk/academic/oil_system_dk2",
  "Seal gas - st.1 (Упл. Газ ст.1 ДК2).fxml": "/sverdlovsk/academic/seal_gas_st1_dk2",
  "Seal gas - st.2,3 (Упл. Газ ст.2,3 ДК2).fxml": "/sverdlovsk/academic/seal_gas_st2-3_dk2",
  "Gas system (Газовая система ДК2).fxml": "/sverdlovsk/academic/gas_system_dk2",
  "Sensors (Датчики ДК2).fxml": "/sverdlovsk/academic/sensors_dk2",
  "Sensors MMS (Датчики MMS ДК2).fxml": "/sverdlovsk/academic/sensors_mms_dk2",
  "Filter system (фильтрующая установка).fxml": "/sverdlovsk/academic/filter_system",
  "Reduction unit (Редукционная установка).fxml": "/sverdlovsk/academic/reduction_unit",
  "Controls AB (Управление компрессорами).fxml": "/sverdlovsk/academic/controls_ab",
  "GAS AB (Система газа).fxml": "/sverdlovsk/academic/gas_ab",
  "Nitrogen (Азотная установка).fxml": "/sverdlovsk/academic/nitrogen",
  "Схема азотной станции.fxml": "/sverdlovsk/academic/shema_azotnoy_stancii",

  //ГТ
  "AIR INTAKE RUS.fxml": "/sverdlovsk/academic/air_intake",
  "COOLING AIR RUS.fxml": "/sverdlovsk/academic/cooling_air",
  "ELECTRICAL RUS.fxml": "/sverdlovsk/academic/elektrikal",
  "FUEL GAS RUS.fxml": "/sverdlovsk/academic/fuel_gas",
  "GENERATOR RUS.fxml": "/sverdlovsk/academic/generator_rus",
  "HYDRAULIK TRIP UNIT RUS.fxml": "/sverdlovsk/academic/hydraulik_trip_unit",
  "LUBE OIL RUS.fxml": "/sverdlovsk/academic/lube_oil",
  "OVERVIEW RUS.fxml": "/sverdlovsk/academic/overview",
  "RELEASE CONDITION RUS.fxml": "/sverdlovsk/academic/release_condition",
  "SHAFT RUS.fxml": "/sverdlovsk/academic/shaft",
  "COMBI STATIC STARTING DEVICE RUS.fxml": "/sverdlovsk/academic/combi_static_starting_device",
  "TRIP RUS.fxml": "/sverdlovsk/academic/trip",
  "POOL RUS.fxml": "/sverdlovsk/academic/pool",
  "TAT MEASUREMENT RUS.fxml": "/sverdlovsk/academic/tat_measurement",
  "POWER CHART RUS.fxml": "/sverdlovsk/academic/power_char",
  "Воздухоподогреватель КВОУ.fxml": "/sverdlovsk/academic/vozduhopodogrevatel_kvou",
  "Замкнутая система охлаждения.fxml": "/sverdlovsk/academic/zamknutaya_sistema_ohlazhdeniya",

  // КУ
  "Газовый подогреватель конденсата ГПК.fxml": "/sverdlovsk/academic/gazovyy_podogrevatel_kondensata_gpk",
  "Газовый тракт (ГАЗ.ТР).fxml": "/sverdlovsk/academic/gazovyy_trakt",
  "Котел-утилизатор КУ.fxml": "/sverdlovsk/academic/kotyol-utilizator",
  "Маслоснабжение и охлаждение ПЭН ВД.fxml": "/sverdlovsk/academic/maslosnabzhenie_i_ohlazhdenie",
  "Металл БНД БВД КУ.fxml": "/sverdlovsk/academic/metall_bnd_bvd_ku",
  "Мехвеличины и температурный контроль.fxml": "/sverdlovsk/academic/mehanicheskie_velichiny_i_temperaturnyy_kontrol",
  "Пароводяной тракт высокого давления.fxml": "/sverdlovsk/academic/parovodyanoy_trakt_vysokogo_davleniya",
  "Пароводяной тракт низкого давления.fxml": "/sverdlovsk/academic/parovodyanoy_trakt_nizkogo_davleniya",
  "Питательно-деаэраторная установка.fxml": "/sverdlovsk/academic/pitatelno-deaeratornaya_ustanovka",
  "Температура холодных спаев КУ.fxml": "/sverdlovsk/academic/temperatura_holodnyh_spaev",
  
  // Защиты
  "Защиты ПК.fxml": "/sverdlovsk/academic/zashchity_pk",
  "Локальные защиты вентиляторов №1,2.fxml": "/sverdlovsk/academic/lokalnye_zashchity_ventilyatorov_1,2",
  "Локальные защиты вентиляторов №3,4.fxml": "/sverdlovsk/academic/lokalnye_zashchity_ventilyatorov_3,4",
  "Локальные защиты ДЭН РЭН.fxml": "/sverdlovsk/academic/llokalnye_zashchity_den_ren",
  "Локальные защиты и разгрузка.fxml": "/sverdlovsk/academic/lokalnye_zashchity_i_razgruzka",
  "Локальные защиты НСВ и НИВ.fxml": "/sverdlovsk/academic/lokalnye_zashchity_nsv_i_niv",
  "Локальные защиты ПЭН ВД №1.fxml": "/sverdlovsk/academic/lokalnye_zashchity_pen_vd_1",
  "Локальные защиты ПЭН ВД №2.fxml": "/sverdlovsk/academic/lokalnye_zashchity_pen_vd_2",
  "Локальные защиты ПЭН НД.fxml": "/sverdlovsk/academic/lokalnye_zashchity_pen_nd",
  "Локальные защиты ЦН 1-4.fxml": "/sverdlovsk/academic/lokalnye_zashchity_cn_1-4",
  "Останов КУ.fxml": "/sverdlovsk/academic/ostanov_ku",
  "Останов ПГУ.fxml": "/sverdlovsk/academic/ostanov_pgu",

  // ПТ
  "Паровая турбина.fxml": "/sverdlovsk/academic/parovaya_turbina",
  "ГП и БРОУ.fxml": "/sverdlovsk/academic/gp_i_brou",
  "Система управления турбины.fxml": "/sverdlovsk/academic/sistema_upravleniya_turbiny",
  "Температурный контроль металла ПТУ.fxml": "/sverdlovsk/academic/temperaturnyy_kontrol_metalla_ptu",
  "Температурный контроль 13 ступени ПТ.fxml": "/sverdlovsk/academic/temperaturnyy_kontrol_13_stupeni_pt",
  "Контроль механических величин турбины.fxml": "/sverdlovsk/academic/kontrol_mehanicheskih_velichin_turbiny",
  "Конденсатор.fxml": "/sverdlovsk/academic/kondensator",
  "Подогреватели сетевой воды.fxml": "/sverdlovsk/academic/podogrevateli_setevoy_vody",
  "Эжекторная установка.fxml": "/sverdlovsk/academic/ezhektornaya_ustanovka",
  "Система уплотнений и дренажей.fxml": "/sverdlovsk/academic/sistema_uplotneniy_i_drenazhey",
  "Система маслоснабжения турбины.fxml": "/sverdlovsk/academic/sistema_maslosnabzheniya_turbiny",
  "Циркуляционная система конденсатора.fxml": "/sverdlovsk/academic/cirkulyacionnaya_sistema_kondensatora",
  "Температурный контроль подшип. насосов.fxml": "/sverdlovsk/academic/temperaturnyy_kontrol_podship_nasosov",
  
  //СТЗиР
  "Паропроводы ПТ.fxml": "/sverdlovsk/academic/paroprovody_pt",
  "Механические величины ПТ.fxml": "/sverdlovsk/academic/mehanicheskie_velichiny_pt",
  "Система регулирования.fxml": "/sverdlovsk/academic/sistema_regulirovaniya",
  "ТЗ, действующие на останов ПТ (ШЗ).fxml": "/sverdlovsk/academic/tz,_deystvuyushchie_na_ostanov_pt_(shz)",
  "ТЗ, действующие на останов ПТ (ЭЧСР).fxml": "/sverdlovsk/academic/tz,_deystvuyushchie_na_ostanov_pt_(echsr)",
  "ТЗ, действующие на отключение ПСГ.fxml": "/sverdlovsk/academic/tz,_deystvuyushchie_na_otklyuchenie_psg",
  "РД ОО.fxml": "/sverdlovsk/academic/rd_oo",
  "Предохранительные регуляторы.fxml": "/sverdlovsk/academic/predohranitelnye_regulyatory",
  "Проверки ПТ.fxml": "/sverdlovsk/academic/proverki_pt",

  //СТМПГ
  "Температурный контроль генератора.fxml": "/sverdlovsk/academic/temperaturnyy_kontrol_generatora",
  
  //ОСО
  "Состояние ВПУ.fxml": "/sverdlovsk/academic/sostoyanie_vpu",
  "Управление ПГУ.fxml": "/sverdlovsk/academic/upravlenie_pgu",
  "Сигнализация.fxml": "/sverdlovsk/academic/signalizaciya",
  "Технологическая общестанционная.fxml": "/sverdlovsk/academic/tehnologicheskaya_obshchestancionnaya",
  "Общестанционное оборудование ГК.fxml": "/sverdlovsk/academic/obshchestancionnoe_oborudovanie_gk",
  "Насосы сетевые 1 подъёма.fxml": "/sverdlovsk/academic/nasosy_setevye_1_podyoma",
  "Температурный контроль насосов.fxml": "/sverdlovsk/academic/temperaturnyy_kontrol_nasosov",
  "ПИВ и баки чистого конденсата.fxml": "/sverdlovsk/academic/piv_i_baki_chistogo_kondensata",
  "БНТ,ДМБ,БГК.fxml": "/sverdlovsk/academic/bnt,dmb,bgk",
  "Техническая вода.fxml": "/sverdlovsk/academic/tehnicheskaya_voda",
  "Газопровод к ГТУ.fxml": "/sverdlovsk/academic/gazoprovod_k_gtu",
  "УКУТ.fxml": "/sverdlovsk/academic/ukut",
  "Мощность ГТУ.fxml": "/sverdlovsk/academic/moshchnost_gtu",
  "Коллекторная.fxml": "/sverdlovsk/academic/kollektornaya",
  "Сетевая вода АкТЭЦ.fxml": "/sverdlovsk/academic/setevaya_voda_aktec",
  "РМБ.fxml": "/sverdlovsk/academic/rmb",
  
  //ВУ
  "Циркнасосы.fxml": "/sverdlovsk/academic/cirknasosy",
  "Циркводоводы.fxml": "/sverdlovsk/academic/cirkvodovody",
  "Опорожнение, дренаж.fxml": "/sverdlovsk/academic/oporozhnenie_drenazh",
  "Паровой котел №1.fxml": "/sverdlovsk/academic/parovoy_kotel_no1",
  "Паровой котел №2.fxml": "/sverdlovsk/academic/parovoy_kotel_no2",
  "ОКО паровых котлов.fxml": "/sverdlovsk/academic/oko_parovyh_kotlov",
  "Горелка ГМ-7 парового котла №1.fxml": "/sverdlovsk/academic/gorelka_gm-7_parovogo_kotla_no1",
  "Горелка ГМ-7 парового котла №2.fxml": "/sverdlovsk/academic/gorelka_gm-7_parovogo_kotla_no2",
  "Насосы дренажных приямков машзала.fxml": "/sverdlovsk/academic/nasosy_drenazhnyh_priyamkov",
  // ФГУ
  "Пуск блока.fxml": "/sverdlovsk/academic/pusk_bloka",
  "Настройки ФГУ ПК.fxml": "/sverdlovsk/academic/nastroyki_fgu_pk",
  "Список ФГУ ПК.fxml": "/sverdlovsk/academic/spisok_fgu_pk",

 

  // hidden
  "ФГУ Розжиг на газе ПК1.fxml": "/sverdlovsk/academic/fgu_rozzhig_na_gaze_pk1",
  "Ошибки выполнения (Розжиг на газе ПК1).fxml": "/sverdlovsk/academic/oshibki_vypolneniya_(rozzhig_na_gaze_pk1)",
  "Условия запуска (Розжиг на газе ПК1).fxml": "/sverdlovsk/academic/usloviya_zapuska_(rozzhig_na_gaze_pk1)",
  "ФГУ Заполнение котла ПК1.fxml": "/sverdlovsk/academic/fgu_zapolnenie_kotla_pk1",
  "Ошибки выполнения (Заполнение котла ПК1).fxml": "/sverdlovsk/academic/oshibki_vypolneniya_(zapolnenie_kotla_pk1)",
  "Условия запуска (Заполнение котла ПК1).fxml": "/sverdlovsk/academic/usloviya_zapuska_(zapolnenie_kotla_pk1)",
  "ФГУ Периодической продувки ПК1.fxml": "/sverdlovsk/academic/fgu_periodicheskoy_produvki_pk1",
  "Ошибки выполнения (Периодической продувки ПК1).fxml": "/sverdlovsk/academic/oshibki_vypolneniya_(periodicheskoy_produvki_pk1)",
  "Условия запуска (Периодической продувки ПК1).fxml": "/sverdlovsk/academic/usloviya_zapuska_(periodicheskoy_produvki_pk1)",
  "ФГУ Останов на газе ПК1.fxml": "/sverdlovsk/academic/fgu_ostanov_na_gaze_pk1",
  "Ошибки выполнения (Останов на газе ПК1).fxml": "/sverdlovsk/academic/oshibki_vypolneniya_(ostanov_na_gaze_pk1)",
  "Условия запуска (Останов на газе ПК1).fxml": "/sverdlovsk/academic/usloviya_zapuska_(ostanov_na_gaze_pk1)",
  "ФГУ Вентиляция топки ПК1.fxml": "/sverdlovsk/academic/fgu_ventilyaciya_topki_pk1",
  "Ошибки выполнения (Вентиляция топки ПК1).fxml": "/sverdlovsk/academic/oshibki_vypolneniya_(ventilyaciya_topki_pk1)",
  "Условия запуска (Вентиляция топки ПК1).fxml": "/sverdlovsk/academic/usloviya_zapuska_(ventilyaciya_topki_pk1)",
  "ФГУ Опрессовка газового блока ПК1.fxml": "/sverdlovsk/academic/fgu_opressovka_gazovogo_bloka_pk1",
  "Ошибки выполнения (Опрессовка газового блока ПК1).fxml": "/sverdlovsk/academic/oshibki_vypolneniya_(opressovka_gazovogo_bloka_pk1)",
  "Условия запуска (Опрессовка газового блока ПК1).fxml": "/sverdlovsk/academic/usloviya_zapuska_(opressovka_gazovogo_bloka_pk1)",
  // 2 part
  "ФГУ Розжиг на газе ПК2.fxml": "/sverdlovsk/academic/fgu_rozzhig_na_gaze_pk2",
  "Ошибки выполнения (Розжиг на газе ПК2).fxml": "/sverdlovsk/academic/oshibki_vypolneniya_(rozzhig_na_gaze_pk2)",
  "Условия запуска (Розжиг на газе ПК2).fxml": "/sverdlovsk/academic/usloviya_zapuska_(rozzhig_na_gaze_pk2)",
  "ФГУ Заполнение котла ПК2.fxml": "/sverdlovsk/academic/fgu_zapolnenie_kotla_pk2",
  "Ошибки выполнения (Заполнение котла ПК2).fxml": "/sverdlovsk/academic/oshibki_vypolneniya_(zapolnenie_kotla_pk2)",
  "Условия запуска (Заполнение котла ПК2).fxml": "/sverdlovsk/academic/usloviya_zapuska_(zapolnenie_kotla_pk2)",
  "ФГУ Периодической продувки ПК2.fxml": "/sverdlovsk/academic/fgu_periodicheskoy_produvki_pk2",
  "Ошибки выполнения (Периодической продувки ПК2).fxml": "/sverdlovsk/academic/oshibki_vypolneniya_(periodicheskoy_produvki_pk2)",
  "Условия запуска (Периодической продувки ПК2).fxml": "/sverdlovsk/academic/usloviya_zapuska_(periodicheskoy_produvki_pk2)",
  "ФГУ Останов на газе ПК2.fxml": "/sverdlovsk/academic/fgu_ostanov_na_gaze_pk2",
  "Ошибки выполнения (Останов на газе ПК2).fxml": "/sverdlovsk/academic/oshibki_vypolneniya_(ostanov_na_gaze_pk2)",
  "Условия запуска (Останов на газе ПК2).fxml": "/sverdlovsk/academic/usloviya_zapuska_(ostanov_na_gaze_pk2)",
  "ФГУ Вентиляция топки ПК2.fxml": "/sverdlovsk/academic/fgu_ventilyaciya_topki_pk2",
  "Ошибки выполнения (Вентиляция топки ПК2).fxml": "/sverdlovsk/academic/oshibki_vypolneniya_(ventilyaciya_topki_pk2)",
  "Условия запуска (Вентиляция топки ПК2).fxml": "/sverdlovsk/academic/usloviya_zapuska_(ventilyaciya_topki_pk2)",
  "ФГУ Опрессовка газового блока ПК2.fxml": "/sverdlovsk/academic/fgu_opressovka_gazovogo_bloka_pk2",
  "Ошибки выполнения (Опрессовка газового блока ПК2).fxml": "/sverdlovsk/academic/oshibki_vypolneniya_(opressovka_gazovogo_bloka_pk2)",
  "Условия запуска (Опрессовка газового блока ПК2).fxml": "/sverdlovsk/academic/usloviya_zapuska_(opressovka_gazovogo_bloka_pk2)",
  // дополнительные по ВК
  "Вентиляция топки ВК-1.fxml": "/sverdlovsk/academic/ventilyaciya_topki_vk-1",
  "ФГУ Опрессовка ВК-1.fxml": "/sverdlovsk/academic/fgu_opressovka_vk-1",
  "Розжиг ЗЗУ ВК-1.fxml": "/sverdlovsk/academic/fgu_rozzhig_zzu_vk-1",
  "Розжиг горелок ВК-1.fxml": "/sverdlovsk/academic/fgu_rozzhig_gorelok_vk-1",
  "Переход Раст-Осн ВК-1.fxml": "/sverdlovsk/academic/fgu_perehod_rast-osn_vk-1",
  "Переход Осн-Раст ВК-1.fxml": "/sverdlovsk/academic/fgu_perehod_osn-rast_vk-1",

  "ФГУ Опрессовка ВК-2.fxml": "/sverdlovsk/academic/fgu_opressovka_vk-2",
  "Розжиг ЗЗУ ВК-2.fxml": "/sverdlovsk/academic/fgu_rozzhig_zzu_vk-2",
  "Розжиг горелок ВК-2.fxml": "/sverdlovsk/academic/fgu_rozzhig_gorelok_vk-2",
  "Переход Раст-Осн ВК-2.fxml": "/sverdlovsk/academic/fgu_perehod_rast-osn_vk-2",
  "Переход Осн-Раст ВК-2.fxml": "/sverdlovsk/academic/fgu_perehod_osn-rast_vk-2",
  "Вентиляция топки ВК-2.fxml": "/sverdlovsk/academic/ventilyaciya_topki_vk-2",






  //ВГ
  "ВГ Академическая-1.fxml": "/sverdlovsk/academic/akademicheskaya-1",
  "ВГ Академическая-2.fxml": "/sverdlovsk/academic/akademicheskaya-2",

  //Мониторинг ША
  "Шкафы ОСО.fxml": "/sverdlovsk/academic/shkafy_oso",
  "Шкафы ВПУ.fxml": "/sverdlovsk/academic/shkafy_vpu",
  "Шкафы ВК.fxml": "/sverdlovsk/academic/shkafy_vk",
  "Шкафы СТЗиР.fxml": "/sverdlovsk/academic/shkafy_stzir",
  "Шкафы ГТУ.fxml": "/sverdlovsk/academic/shkafy_gtu",
  "Защитные сигналы ОСО.fxml": "/sverdlovsk/academic/zashchitnye_signaly_oso",
  "Защитные сигналы КУ.fxml": "/sverdlovsk/academic/zashchitnye_signaly_ku",
  "Шкафы ПК.fxml": "/sverdlovsk/academic/shkafy_pk",
  "Шкафы ПТК.fxml": "/sverdlovsk/academic/shkafy_ptk",

  //ВК
  "Газоснабжение ВК-1.fxml": "/sverdlovsk/academic/gazosnabzhenie_vk1",
  "Газовоздушная часть.fxml": "/sverdlovsk/academic/gazovozdushnaya_chast_vk1",
  "Горелка №1 ВК-1.fxml": "/sverdlovsk/academic/gorelka_1_vk1",
  "Горелка №2 ВК-1.fxml": "/sverdlovsk/academic/gorelka_2_vk1",
  "Горелка №3 ВК-1.fxml": "/sverdlovsk/academic/gorelka_3_vk1",
  "Горелка №4 ВК-1.fxml": "/sverdlovsk/academic/gorelka_4_vk1",
  "Насосы рециркуляции ВК-1.fxml": "/sverdlovsk/academic/nasosy_recirkulyacii_vk1",
  "Калориферы ВК-1.fxml": "/sverdlovsk/academic/kalorifery_vk1",
  "Газоснабжение ВК-2.fxml": "/sverdlovsk/academic/gazosnabzhenie_vk2",
  "Газовоздушная часть ВК-2.fxml": "/sverdlovsk/academic/gazovozdushnaya_chast_vk2",
  "Горелка №1 ВК-2.fxml": "/sverdlovsk/academic/gorelka_1_vk2",
  "Горелка №2 ВК-2.fxml": "/sverdlovsk/academic/gorelka_2_vk2",
  "Горелка №3 ВК-2.fxml": "/sverdlovsk/academic/gorelka_3_vk2",
  "Горелка №4 ВК-2.fxml": "/sverdlovsk/academic/gorelka_4_vk2",
  "Общая тепловая ВК.fxml": "/sverdlovsk/academic/obshchaya_teplovaya_vk2",
  "Насосы рециркуляции ВК-2.fxml": "/sverdlovsk/academic/nasosy_recirkulyacii_vk2",
  "Калориферы ВК-2.fxml": "/sverdlovsk/academic/kalorifery_vk2",
  "Врезка в сеть.fxml": "/sverdlovsk/academic/vrezki_v_set",
  "Температурный контроль.fxml": "/sverdlovsk/academic/temperaturnyy_kontrol",
  "Индивидуальный тепловой пункт.fxml": "/sverdlovsk/academic/individualnyy_teplovoy_punkt",
  "Защиты на останов ВК1.fxml": "/sverdlovsk/academic/zashchity_na_ostanov_vk1",
  "Локальные защиты ВК1.fxml": "/sverdlovsk/academic/lokalnye_zashchity_vk1",
  "Локальные защиты горелок ВК1.fxml": "/sverdlovsk/academic/lokalnye_zashchity_gorelok_vk1",
  "Защиты на останов ВК2.fxml": "/sverdlovsk/academic/zashchity_na_ostanov_vk2",
  "Локальные защиты ВК2.fxml": "/sverdlovsk/academic/lokalnye_zashchity_vk2",
  "Локальные защиты горелок ВК2.fxml": "/sverdlovsk/academic/lokalnye_zashchity_gorelok_vk2",
  // "Вентиляция топки ВК-1.fxml": "/sverdlovsk/academic/ventilyaciya_topki_vk-1",
  // "Вентиляция топки ВК-2.fxml": "/sverdlovsk/academic/ventilyaciya_topki_vk-2",



  //ЭСО
  "Главная схема.fxml": "/sverdlovsk/academic/glavnaya_shema",
  "КРУЭ 110 кВ.fxml": "/sverdlovsk/academic/krue110",
  "Противоаварийная автоматика.fxml": "/sverdlovsk/academic/protivoavariynaya_avtomatika",
  "Генератор.fxml": "/sverdlovsk/academic/generator",
  "Приборы и защиты.fxml": "/sverdlovsk/academic/pribory_i_zashchity",
  "РУ 10-6 кВ.fxml": "/sverdlovsk/academic/ru_10-6_kv",
  "РУСН 0.4 кВ ПВК.fxml": "/sverdlovsk/academic/rusn_04_kv_pvk",
  "РУСН 0.4 кВ.fxml": "/sverdlovsk/academic/rusn_04_kv",
  "РУСН 6 кВ.fxml": "/sverdlovsk/academic/rusn_6_kv",
  "Сетевая насосная станция.fxml": "/sverdlovsk/academic/setevaya_nasosnaya_stanciya",



  };
